name: Newman Run

on:
  pull_request:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMANAPIKEY }}
          collection: 38790537-07126bb3-bfa0-4e14-a17e-12003c8b5a80
